# This is a basic workflow to help you get started with Actions

name: AutoBuild for Windows
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  create:
    tags:
      - v*
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/node12-win-x86.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}